db_name: cifar-10
total_epoch: 200
data_parallel: True
log_dir: ./results/select/cifar-10
#ckpt_dir: ./results/cifar-10

plot_freq: 2
noise_rate: 0.2
loss_logger:
  name: TopkLossLogger
  topk_rate: 0.2


model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss
  reduction: none

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0