db_name: cifar-10
total_epoch: 200
data_parallel: True
result_dir: ./results/select/cifar-10
ckpt_dir: null

plot_freq: 20
noise_rate: 0.2
loss_logger:
  name: ThreLossLogger
  thre_loss: 2.5

model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss
  reduction: none

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0