db_name: imagenet_mini
total_epoch: 200
data_parallel: True
result_dir: ./results/imagenet_mini
#ckpt_dir: ./results/imagenet_mini

plot_freq: 2
noise_rate: 0.2
loss_logger:
  name: TopkLossLogger
  topk_rate: 0.2


model:
  name: resnet18
  num_classes: 100


criterion:
  name: CrossEntropyLoss
  reduction: none

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0