db_name: tiny_imagenet
total_epoch: 80
data_parallel: True
result_dir: ./results/tiny_imagenet
#ckpt_dir: ./results/tiny_imagenet

plot_freq: 2
noise_rate: 0.2
loss_logger:
  name: TopkLossLogger
  topk_rate: 0.2


model:
  name: resnet18
  num_classes: 1000


criterion:
  name: CrossEntropyLoss
  reduction: none

optimizer:
  name: SGD
  lr: 1e-1
  weight_decay: 5.e-5
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0