db_name: svhn
total_epoch: 60
data_parallel: True
result_dir: ./results/svhn
#ckpt_dir: ./results/svhn

plot_freq: 20
noise_rate: 0.2
loss_logger:
  name: TopkLossLogger
  topk_rate: 0.2

model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss
  reduction: none

optimizer:
  name: SGD
  lr: 0.001
  weight_decay: 5e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0