db_name: imagenet
total_epoch: 200
data_parallel: True
log_dir: ./results/imagenet
ckpt_dir: ./results/imagenet
noise_rate: 0.2

model:
  name: resnet18
  num_classes: 1000


criterion:
  name: CrossEntropyLoss
  reduction: none

optimizer:
  name: SGD
  lr: 1e-1
  weight_decay: 5e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0