db_name: svhn
total_epoch: 200
data_parallel: True
log_dir: ./results/ue/svhn
#ckpt_dir: ./results/ue/svhn
noise_path: ./results/select/svhn

plot_freq: 2
noise_rate: 0.2

attack:
  name: PGD
  eps: 8
  alpha: 0.8
  steps: 20


model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss


optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5e-5
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0