db_name: cifar-10
total_epoch: 200
log_dir: ./results/ue/cifar-10
#ckpt_dir: ./results/ue/cifar-10
noise_path: ./results/select/cifar-10

plot_freq: 2
noise_rate: 0

attack:
  name: PGD
  eps: 8
  alpha: 1
  steps: 20


model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss


optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5e-5
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0