db_name: cifar-10
total_epoch: 60
data_parallel: True
result_dir: ./results/train_with_ue/cifar-10
#ckpt_dir: ./results/train_with_ue/cifar-10
ckpt_dir: null
noise_path: ./results/select/cifar-10/noise_idx.pt
perturbfile_path: ./results/ue/cifar-10/perturbation.pt
hl_perturbfile_path: ./results/ue/cifar-10/hl_perturbation.pt
#noise_path: null
#hl_perturbfile_path: null

plot_freq: 2
noise_rate: 0.2

model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss


optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5e-5
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0