db_name: cifar-10
total_epoch: 60
data_parallel: True
log_dir: ./results/train_with_target_ue/cifar-10
ckpt_dir: null
#noise_path: ./results/select/cifar-10
perturbfile_path: ./results/target_ue/cifar-10/perturbation.pt

model:
  name: ResNet18
  num_classes: 10


criterion:
  name: CrossEntropyLoss


optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5e-5
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: ${total_epoch}
  eta_min: 0.0